export const BASE_URL = 'https://api.themoviedb.org/3';
export const API_KEY = '3bb7c750e6d9b2ae7509ab17b85a7611';
export const LIBRARY_STATUS = 'LibraryStatus';
export const WATCHED = 'WATCHED';
export const QUEUE = 'QUEUE';
export const btnWatchTextContentRemove = 'REMOVE FROM WATCHED';
export const btnQueueTextContentRemove = 'REMOVE FROM QUEUE';
export const btnWatchTextContent = 'ADD TO WATCHED';
export const btnQueueTextContent = 'ADD TO QUEUE';
